version: '3'
services:
  gateway:
    build: ./gateway-nestjs
    ports:
      - "3000:3000"
    depends_on:
      - order-service
      - user-service
    volumes:
      - ./proto:/app/proto

  user-service:
    build: ./user-nestjs-service
    ports:
      - "50052:50052"

  order-service:
    build: ./order-springboot-service
    ports:
      - "50051:50051"
