grpc:
  client:
    local-grpc-server:
      address: static://localhost:50051 # Cấu hình phía client, có thể không liên quan nếu dịch vụ thông báo chỉ là máy chủ.
      negotiationType: plaintext

  server:
    port: 50051 # Đây là cổng gRPC server, được API Gateway sử dụng.
    address: 0.0.0.0

server:
  port: 30001 # Đây là cổng HTTP server của Spring Boot. Nếu không cần thiết cho truy cập trực tiếp/kiểm tra sức khỏe, có thể xóa hoặc đặt thành 0.

spring:
  datasource:
    url: jdbc:postgresql://103.75.184.206:3307/micro_matching
    username: root
    password: gennydev@123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect